### ISSUE TITLE
generator-polymer-init-custom-build' is not in the npm registry.

### ISSUE THREAD

**Issue by juanpicuervo** [PolymerElements/generator-polymer-init-custom-build#10]
When i try to run the command npm install -g generator-polymer-init-custom-build  it gives me the following error:

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/generator-polymer-init-custom-build
npm ERR! 404 
npm ERR! 404 'generator-polymer-init-custom-build' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by chuckh** [comment]
This repo is a WIP, it is not yet in the NPM registry.

**Comment by robdodson** [comment]
yeah sorry. To try it out right now you'll need to clone the repo and run `npm link`

**Comment by robdodson** [comment]
Just published 0.1.0 to npm
