### ISSUE TITLE
Better error message for wrong polymer.json definition 

### ISSUE THREAD

**Issue by timeu** [PolymerElements/generator-polymer-init-custom-build#28]
Took me a while to find the issue, when migrating an existing polymer app to the new build tool. 

When there an non-existing polymer element is referenced in the polymer.json file, gulp will output following error message:

```bash
[23:28:02] The following tasks did not complete: default, output                                                                           
[23:28:02] Did you forget to signal async completion?  
```

This is with logging turned on in the gulpfile.js.

**Comment by robdodson** [comment]
Would you mind moving this issue to https://github.com/Polymer/polymer-build?

**Comment by timeu** [comment]
Moved to https://github.com/Polymer/polymer-build/issues/29

**Comment by robdodson** [comment]
Thanks!
