### ISSUE TITLE
How to extend polymer serve?

### ISSUE THREAD

**Issue by davidsteinberger** [PolymerElements/generator-polymer-init-custom-build#29]
Is there a possibility to extend `polymer serve` or is there a standard _escape hatch_ (similar to the default gulp tasks that replaces `polymer build`) to spin up a development proxy to directly work with backend apis?

**Comment by robdodson** [comment]
I think this is more of a Polymer CLI question. Would you mind moving the issue to https://github.com/Polymer/polymer-cli ?

**Comment by davidsteinberger** [comment]
This issue was moved to Polymer/polymer-cli#387

**Comment by davidsteinberger** [comment]
@robdodson Sure, np. Do you have any personal opinion on that? IMO, that'd make a fantastic (future) _Polymer Starter Kit 2.1_ polycast episode, isn't it?

**Comment by robdodson** [comment]
I'm imagining you'd probably want to use a gulp task or npm script to startup your own server. The dev server that ships with Polymer CLI is pretty lightweight
