### ISSUE TITLE
README for elements does not indicate that the polymer build command is not applicable

### ISSUE THREAD

**Issue by kito99** [PolymerElements/generator-polymer-init-custom-build#33]
If you use the element template, the README implies that you should still use the `polymer build` command, but if you do, it fails with this error. According to the Polymer CLI docs (https://www.polymer-project.org/1.0/docs/tools/polymer-cli), the build command isn't applicable. 

It also says 'Application' rather than 'Element'.

**Comment by robdodson** [comment]
Are you talking about if you use the element generator from within a custom build project? Can you give me the commands you ran?

**Comment by kito99** [comment]
My bad. I meant to file this with https://github.com/PolymerLabs/generator-polymer-init, but now I see that the code has basically been copied into the CLI source tree (perhaps the separate repository should be removed?). At any rate, I went a head and filed a pull request: https://github.com/Polymer/polymer-cli/pull/391

**Comment by kito99** [comment]
@robdodson, as a side-note, it'd be nice to have support for elements added to the this generator. I was basically trying to do that by starting with the polymer-cli init element and and then adding in stuff from this generator so I could integrate TypeScript support. However, it turns out to be non-trivial, so I'm just reverting back to the handy gulp script I've been using that's derived from PSK 1.0.

**Comment by robdodson** [comment]
@kito99 yeah I want to be able to generate an element within the project. @justinfagnani wdyt about deleting the generator-polymer-init repo?
