### ISSUE TITLE
importing paper-shadow will crash polymer build

### ISSUE THREAD

**Issue by FredKSchott** [PolymerElements/generator-polymer-init-custom-build#34]
_From @timeu on August 29, 2016 22:43_

By accident I imported the depcrecated `paper-shadow` in a fresh `polymer custom-build` app.
When I run `gulp` it will crash in the middle of the build with following error message (even when verbose logging in gulpfile.js is turned on):

```
[23:28:02] The following tasks did not complete: default, output                                                                           
[23:28:02] Did you forget to signal async completion?  
```

To reproduce: 

```
mkdir test
cd test
polymer init custom-build
bower install --save Polymer/paper-shadow
# add html import for paper-shadow into my-app.html
gulp
```

_Copied from original issue: Polymer/polymer-build#30_

**Comment by FredKSchott** [comment]
Possibly related to https://github.com/Polymer/polymer-build/issues/29

**Comment by FredKSchott** [comment]
@timeu can you share the exact code you used to add the html import for paper-shadow into my-app.html?

**Comment by timeu** [comment]
Ok, I checked again and  I think the problem is that `paper-shadow` is a Polymer 0.5 element and thus might have caused the crash. But if you want to reproduce it, just add `<link rel="import" href="../bower_components/paper-shadow/paper-shadow.html">` as the last import.

**Comment by robdodson** [comment]
Yeah you want `bower install --save PolymerElements/paper-shadow`

**Comment by timeu** [comment]
@robdodson : Yeah although `PolymerElements/paper-shadow` does not exist (I think it was moved inside `paper-styles` and `paper-card` respectively. 
But I would argue that the build tool should output a more specific error message instead of the generic one above.

**Comment by robdodson** [comment]
@timeu if it's able to infer this is the cause, sure. That's not something I can fix in the custom-build generator. We need that to come in upstream from polymer-build

**Comment by FredKSchott** [comment]
@robdodson thanks for helping with this :) 
@timeu I agree, we already have a collection of issues around poor error messaging that we'll be addressing over the next few weeks in the polymer-build library.

**Comment by timeu** [comment]
Sounds good, thanks!

Just for context, how I ended up importing `paper-shadow` dependency. 
I was installing `paper-card` but forgot to prefix it with `PolymerElements` and so it ended up to pick up `paper-card` from https://github.com/andytuwm/paper-card which has a dependency on the deprecated `paper-shadow`. It took me a while until I figured out my mistake
