### ISSUE TITLE
Build with es6 support

### ISSUE THREAD

**Issue by m4s0fd1s** [PolymerElements/generator-polymer-init-custom-build#39]
Hi, I tried to integrate es6 support to your custom-build example, so I followed your README and tried to add es6 support.

What I did is:

- adding the corresponding babel task in gulp-task and my gulpfile.js 
- adding the dev-dependencies in package.json
- adding `let es6test = 'mytest';` in my-app.html

The project now compiles and transpiles fine with `gulp`, however with `polymer build` it doesn't and gives me the following error :

`warn:    Unable to optimize .js file /Users/Username/workspace/polymer-custom-build-es6/src/my-app.html_script_0.js
{ err:
   { message: 'SyntaxError: Unexpected token: name (es6test)',
     filename: 0,
     line: 3,
     col: 8,
     pos: 10,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2092:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2100:9)\n    at unexpected (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2106:9)\n    at semicolon (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2126:56)\n    at simple_statement (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2317:73)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2186:19)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2139:24)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2907:23)' } }`

If you want to reproduce the error, just check-out the test, it's the basic custom build, with the modification above + gulp-debug to show which files are transpiled

https://github.com/m4s0fd1s/polymer-custom-build-es6

and run `bower install`, `npm install`, `polymer build` or alternatively `gulp`

**Comment by robdodson** [comment]
`polymer build` doesn't run the underlying gulp file. The gulpfile is meant to act as a replacement for the `polymer build` command. So, if you're using custom-build, don't use `polymer build`
