### ISSUE TITLE
Vulcanize Crisper Babel not working

### ISSUE THREAD

**Issue by juanpicuervo** [PolymerElements/generator-polymer-init-custom-build#43]
Hi, im trying to optimize my code using  Vulcanize Crisper Babel  (https://www.polymer-project.org/1.0/docs/tools/optimize-for-production). I add the following code to my gulpfile.js in order to make this and i have the following error:

**The following tasks did not complete: default, output
Did you forget to signal async completion?**

`function source() {
  return project.splitSource()
    // Add your own build tasks here!         
    .pipe(gulpif('src/*.*',crisper()))
    .pipe(gulpif('src/*.js',babel()))
    .pipe(gulpif('src/*.html', strip()))
    .pipe(gulpif('**/*.{png,gif,jpg,svg}', images.minify()))
    .pipe(gulpif('src/*.html', minifyInline()))
    .pipe(gulpif('src/*.html', htmlmin({collapseWhitespace: true})))
    .pipe(project.rejoin()); // Call rejoin when you're finished
}`

Is there any way to implement this?

**Comment by robdodson** [comment]
you shouldn't need to add vulcanize or crisper as both of those are handled for you by the library. In fact, adding them again to the build will probably break things. Try removing all of those tasks you added except for `.pipe(gulpif('src/*.js',babel()` and let me know if that works.

**Comment by juanpicuervo** [comment]
Thanks @robdodson, removing those lines it works !

`  return project.splitSource()
    .pipe(gulpif('**/*.js', uglify()))
    .pipe(gulpif('src/**/*.js',babel({
            presets: ['es2015']
        })))
    .pipe(gulpif('**/*.{png,gif,jpg,svg}', images.minify()))
    .pipe(project.rejoin()); `

**Comment by robdodson** [comment]
yay! \o/
