### ISSUE TITLE
$ Gulp | TypeError: Cannot read property 'apply' of undefined ... (Windows 10)

### ISSUE THREAD

**Issue by oneezy** [PolymerElements/generator-polymer-init-custom-build#44]
# TypeError: Cannot read property 'apply' of undefined ... (Windows 10)

Following the steps in @robdodson 's Polycast `#52` video, I'm running into a TypeError issue when running the `$ gulp` command from inside a Windows 10 OS.

Any ideas?

> Note: I upgraded Node to `v7.0.0` after it failed running in `v6.3.0` , but this didn't do the trick.

-----

**Details:**

```
Oneeezy@Oneezy MINGW64 ~/Desktop/custom-build
$ git --version
git version 2.10.1.windows.1

$ node -v
v7.0.0

$ npm -v
3.10.8

$ bower -v
1.7.9

$ gulp -v
[04:50:58] CLI version 3.9.1
[04:50:58] Local version 4.0.0-alpha.2

$ polymer --version
0.16.0

Oneeezy@Oneezy MINGW64 ~/Desktop/custom-build
$ gulp
[04:32:00] Using gulpfile ~\Desktop\custom-build\gulpfile.js
C:\Users\Oneeezy\AppData\Roaming\nvm\v7.0.0\node_modules\gulp\bin\gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at C:\Users\Oneeezy\AppData\Roaming\nvm\v7.0.0\node_modules\gulp\bin\gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

```

**Comment by abdonrd** [comment]
@oneezy Try with `node_modules/gulp/bin/gulp.js`.

**Comment by oneezy** [comment]
Thanks for your super quick reply @abdonrd !

Sorry if this is a dumb questions, but how would I run `$ gulp` locally from the project? 

I've only ever used the global approach with it.

**Comment by abdonrd** [comment]
Your welcome! :)

The [custom-build uses gulp#4.0](https://github.com/PolymerElements/generator-polymer-init-custom-build/blob/master/generators/app/package.json#L19) and your gulp global version is `v3.9.1`.

With #41 we should fix this issue.

**Comment by oneezy** [comment]
Ah snap, gotcha. 

Thanks man. I'll get on that upgrade.
