### ISSUE TITLE
Better compilation debug output for mis-named source files

### ISSUE THREAD

**Issue by learmond** [PolymerElements/generator-polymer-init-custom-build#45]
I'm building a very simple es6 test app using gulp-babel and I encountered a somewhat misleading or vague error during `gulp-ification`.
I have a javascript source file (lets call it util.js) next to the my-app.html and I include it like any other javascript file:

```
// in my-app.html
<link rel="import" href="../bower_components/polymer/polymer.html">
...
<script type="text/javascript" src="/src/utils.js"></script>

<dom-module id="my-app">
...
```

As you can see, I've mistakenly tried to bring in '/src/utils.js' instead of '/src/util.js'.
With verbose logging enabled in `gulpfile.js`, compilation outputs the following:

```
...
debug:   accept: src/my-app.html
debug:   accept: /src/utils.js
debug:   dependency is a source file, ignoring... 
{ dep: '/src/utils.js' }
debug:   accept: bower_components/polymer/polymer.html

... proceed to process the rest of the source/images ... then

[14:59:25] gulp-imagemin: Minified 6 images (saved 9.54 kB - 24.1%)
[14:59:25] The following tasks did not complete: default, output
[14:59:25] Did you forget to signal async completion?
```

If I name it correctly in the script tag, the compilation completes successfully.

Is there any way to obtain better compilation logging which would provide descriptive/meaningful output for a problem such as this?

Thanks so much! This project is most excellent!

**Comment by robdodson** [comment]
cc @fredkschott

**Comment by FredKSchott** [comment]
see https://github.com/PolymerElements/generator-polymer-init-custom-build/issues/47#issuecomment-264976050

This has been fixed in the latest version of polymer-build, which will be pushed out to the CLI soon

**Comment by robdodson** [comment]
awesooome! thank u @FredKSchott

**Comment by learmond** [comment]
That's Fantoastic! Thank you both.
