### ISSUE TITLE
The following tasks did not complete: default, output Did you forget to signal async completion?

### ISSUE THREAD

**Issue by maury91** [PolymerElements/generator-polymer-init-custom-build#47]
When I run
```bash
gulp
```

I always get
```
...
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/paper-badge/paper-badge.html' }
[10:40:01] The following tasks did not complete: default, output
[10:40:01] Did you forget to signal async completion?
```

I tried to debug by adding in all the streams a ".on('error'..." but nothing is fired, the build simply stop without any reason

Node version: 5.8.0
Gulp version: cli 3.9.1, local 4.0.0-alpha2

I tried even with node 6.9.1, but it stop a lot earlier with 
```
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by abdonrd** [comment]
You need to use `npm run build` or `node_modules/gulp/bin/gulp.js` to use the local gulp version.

**Comment by maury91** [comment]
@abdonrd  already done, same error, it solved only the error with node 6, now node 6 have the same error of node 5

**Comment by maury91** [comment]
This is the full command I'm running to make the environment fresh as possible: 
```bash
n 6.9.1 && rm -rf node_modules bower_components && npm i -g bower && bower i && npm i && npm run build
```

The error is always
```
[10:40:01] The following tasks did not complete: default, output
[10:40:01] Did you forget to signal async completion?
```

Before the error, the task is pretty long, and I suppose is processing all the files, it stops always at the same point, after paper-badge, the process looks pretty deterministic.

**Comment by abdonrd** [comment]
Maybe an issue with the polymer-build? Try with `polymer build`.

**Comment by maury91** [comment]
@abdonrd `polymer build` triggers a lot of warning because I'm using ES6
I don't know if ends correctly, the app produced on _build/_ doesn't work.

**Comment by maury91** [comment]
The app without being build works, if I run `polymer serve` I have a working app on the browser. But isn't something I can ship

**Comment by maury91** [comment]
If I comment out `.pipe(project.analyzer)` and I get the following output

```
[11:36:32] Starting 'output'...
debug:   sourceGlobs:
	... massive list ...
[11:36:34] gulp-imagemin: Minified 14 images (saved 11.1 kB - 5.3%)
source end
[11:36:34] The following tasks did not complete: default, output
[11:36:34] Did you forget to signal async completion?
```

I changed the code as following
```js
function source() {
  return project.splitSource()
  // Add your own build tasks here!
    .pipe(gulpif('**/*.{png,gif,jpg,svg}', images.minify()))
    .pipe(project.rejoin())
    .on('error', (e) => console.error('source error',e))
    .on('end', () => console.log('source end')); // Call rejoin when you're finished
}

// The dependencies task will split all of your bower_components files into one
// big ReadableStream
// You probably don't need to do anything to your dependencies but it's here in
// case you need it :)
function dependencies() {
  return project.splitDependencies()
    .pipe(project.rejoin())
    .on('error', (e) => console.error('dependencies error',e))
    .on('end', () => console.log('dependencies end'));
}
```

So I can assume the problem is in dependencies, cause I see `source end`

**Comment by maury91** [comment]
I get the following conditions:

By commenting in this way: 
```js
const mergedFiles = mergeStream(source()/*, dependencies()*/)
      // .pipe(project.analyzer)
      .on('error', function (err) {
        console.error(err.message);
        process.exit(1);
      });
```
and setting bundleType to 'unbundled' I get the error moved to serviceWorker

```
[11:45:53] gulp-imagemin: Minified 14 images (saved 11.1 kB - 5.3%)
source end
[11:45:53] Finished 'output' after 1.84 s
[11:45:53] Starting 'serviceWorker'...
[11:45:53] The following tasks did not complete: default, serviceWorker
[11:45:53] Did you forget to signal async completion?
```

If I use bundleType  'bundled' or  'both', the task output never ends,
If I include project.analyze or dependencies() output never ends.

I don't know if this can be helpful, but I least I found one condition where the error is moved to another task

**Comment by maury91** [comment]
After changing some things in the app
This command works:
```bash
rm -rf build && polymer build && polymer serve build/unbundled
```

( the issue was related to WebComponentsReady never fired )

`npm run build` still doesn't work

Seems that the issues aren't with polymer build

**Comment by maury91** [comment]
I finally solve it!

I run `polymer lint` and it told me that a file can't be found, I added that file and now `npm run build` works.

So the issue was:
I file is missing but the gulpfile don't show any error

**Comment by robdodson** [comment]
@fredkschott I think there was work being done to log when a file is missing. Has that landed yet or is it still work in progress?

**Comment by FredKSchott** [comment]
The latest version of polymer gets rid of a lot of these silent failures, including when a file is missing. You can check it out now by doing `npm install -g polymer-cli@next` and it should be released to `latest` soon.

**Comment by robdodson** [comment]
w00t
