### ISSUE TITLE
Polymer starter kit does not exist

### ISSUE THREAD

**Issue by gluwer** [PolymerElements/generator-polymer-init-custom-build#53]
Hi,

After installing both polymer-cli and generator as described I receive below error:

error:   Uncaught exception: AssertionError: Trying to copy from a source that does not exist: C:\Users\user\AppData\Roaming\npm\node_modules\generator-polymer-init-custom-build\generators\app\polymer-starter-kit

The temporary fix is to git clone polymer-starter-kit to expected folder, but it shoudn't expect that.

**Comment by robdodson** [comment]
Ah my mistake. I just got a new laptop and hadn't checked out the submodule before publishing. Should be fixed now. You'll want to run `npm install -g generator-polymer-init-custom-build` again to get the latest.
