### ISSUE TITLE
Build is not working properly

### ISSUE THREAD

**Issue by gluwer** [PolymerElements/generator-polymer-init-custom-build#54]
Way to reproduce:

1. Create project as described in README.
2. Sample app works properly using `polymer server` in development mode.
3. Build using `gulp build` and run `polymer server build` and sample app is not working.

After some checking it looks it is something with imports in vulcanized html files (for example shell file has no dependencies inlined and also no imports).

**Comment by robdodson** [comment]
I'm not able to reproduce this. Can you try with the latest version of this generator?

**Comment by gluwer** [comment]
No, after updating to 2.0.1 I see exactly the same as before. I use Windows 10, node 6.9.1.

I've checked standard starter-kit and in bundled version there everything is just fine (my-app.html has all shared deps inside). But in custom-build version my-app.html file is just like version from src but stripped from all dependencies, so something like below:

```
...
--><html><head><meta charset="UTF-8">













</head><body><dom-module id="my-app">
...
```

Maybe it is something related to Windows platform (paths?). When I comment out `fsResolver: this.analyzer.loader,` line in `bundle.js` in `polymer-build`, it seems to work (but of course no css and js minifying), so it also may be that the problem is in the build and not in the generator, but not sure as `polymer build` also uses it and works fine.

**Comment by abdonrd** [comment]
Maybe is it? https://github.com/Polymer/polymer-build/issues/102

**Comment by gluwer** [comment]
My path when testing this is `d:\projects\tesrt`, so not exactly the same issue. Also there are no errors in the build process itself () as in the mentioned Polymer/polymer-build#102.

```
warn:    "sourceGlobs" config option has been renamed to "sources" and will no longer be supported in future versions
warn:    "includeDependencies" config option has been renamed to "extraDependencies" and will no longer be supported in future versions
[16:42:54] Using gulpfile D:\projects\tesrt\gulpfile.js
[16:42:54] Starting 'build'...
Deleting build directory...
Analyzing build dependencies...
[16:42:59] gulp-imagemin: Minified 6 images (saved 9.56 kB - 24.2%)
Generating the Service Worker...
Build complete!
[16:43:02] Finished 'build' after 7.51 s
```

**Comment by robdodson** [comment]
Hm @FredKSchott any thoughts?

**Comment by gluwer** [comment]
Found the real cause (Windows paths with once \ once / and once lowercase and once uppercase drive letter).

Added issue as Polymer/polymer-build#114
