### ISSUE TITLE
Bundled Build Process Removes Dependencies

### ISSUE THREAD

**Issue by fooloomanzoo** [PolymerElements/generator-polymer-init-custom-build#58]
If I follow the instructions:

    npm install -g polymer-cli
    npm install -g generator-polymer-init-custom-build

    polymer init custom-build
    npm run build
    polymer serve build/

The website won't build up:

![image](https://cloud.githubusercontent.com/assets/9318952/22382948/113b1ba8-e4c8-11e6-9b66-0a55d34803f6.png)

because loading `<link rel="import" href="../bower_components/polymer/polymer.html">` is **never initiated**, not by the service-worker nor by `<my-app></my-app>`. The build- and bundeling-process removes the dependencies from the code:

![image](https://cloud.githubusercontent.com/assets/9318952/22383846/e51879b8-e4cb-11e6-92b5-7af50e84ed2a.png)

The other resources dependencies are also removed.
**generator-polymer-init-custom-build** is not working for _polymer-serve_ and not with a usual _express_-server without server-push, because the bundeling is broken.

**Comment by robdodson** [comment]
@FredKSchott does this sound like the build silently errored?

**Comment by FredKSchott** [comment]
This is a known issue in polymer-build (https://github.com/Polymer/polymer-build/issues/110). We are hoping to get a fix out next week.

**Comment by stramel** [comment]
Should be fixed in the latest polymer-build version 0.8.1
