### ISSUE TITLE
no bundled resources are created

### ISSUE THREAD

**Issue by araker** [PolymerElements/generator-polymer-init-custom-build#63]
Hello, I've installed the latest version of this generator (using polymer-build v0.8.1), but after building (npm run build) no bundled resources are created. The script completes successfully and I don't get any error messages. 

I've attached a screenshot of the output in the build folder. 
![screen shot 2017-02-23 at 10 16 04](https://cloud.githubusercontent.com/assets/430230/23254003/cb613550-f9b6-11e6-9d46-ee393fee3be8.png)

I expected to see a shared-bundle.html, or bundles for the defined fragments. I'm new to polymer, so maybe I'm missing something here.

**Comment by robdodson** [comment]
Take a look at src/my-app.html. it should contain the bundled code. Polymer
build doesn't change your file paths so your code can remain simple

**Comment by araker** [comment]
You're totally right, thanks for clearing my misunderstanding.
