### ISSUE TITLE
Update to support multiple builds

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/generator-polymer-init-custom-build#77]
I think we should update to support multiple builds, as `polymer.json` has.

@FredKSchott can you help here? 😄

**Comment by stramel** [comment]
Mind if I take a stab at it this weekend? Anything we are looking to achieve beyond just multiple builds?

**Comment by stramel** [comment]
Got a pretty solid start on it tonight. Will clean it up and put it out for review. Trying to mimic a lot of the polymer-cli/build.

**Comment by abdonrd** [comment]
Thanks @stramel!

**Comment by abdonrd** [comment]
Closing and old issue.
