### ISSUE TITLE
Custom build for polymer 2.0 and es6

### ISSUE THREAD

**Issue by femiadeyemi** [PolymerElements/generator-polymer-init-custom-build#79]
Any plans in making the custom build in polymer 2.0 and es6 compliant?

**Comment by stramel** [comment]
You can check out #78

**Comment by abdonrd** [comment]
Right, we should update PSK version: https://github.com/PolymerElements/generator-polymer-init-custom-build/pull/81

**Comment by abdonrd** [comment]
Done! 🎉 

https://github.com/PolymerElements/generator-polymer-init-custom-build/releases/tag/v3.0.0
